### ISSUE TITLE
Issue with redis, all uplinks are dropped

### ISSUE THREAD

**Issue by alexbn71** [TheThingsNetwork/lorawan-stack#2242]
#### Summary
The newest versions have an issue related with redis that drops all uplinks messages received by nodes.

#### Steps to Reproduce
I use docker-compose.yml with this settings for redis:

```
  redis:
    image: redis
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - ${DEV_DATA_DIR:-.env/data}/redis:/data
    ports:
      - "127.0.0.1:6379:6379"

...
...
...

   environment:
      - TTN_LW_REDIS_ADDRESS=redis:6379
```

#### What do you see now?

dropped uplinks in console and this message in the stack:

WARN Finished unary call                      duration=14.29155ms error=error:pkg/redis:store (store error) error_cause=dial tcp 127.0.0.1:6379: connect: connection refused error_correlation_id=91199bf942f5474f947218d76407fab5 error_name=store error_namespace=pkg/redis grpc_code=Unknown grpc_method=HandleUplink grpc_service=ttn.lorawan.v3.GsNs namespace=grpc request_id=01E46M0W9GGPMWS1FE0G6JHP55
#### What do you want to see instead?

that it works like in v3.6.0

#### Environment

the issue appear after an upgrade to v3.6.1 or v3.6.2.
