### ISSUE TITLE
MQTT Server not reachable/not running

### ISSUE THREAD

**Issue by laubed** [TheThingsNetwork/lorawan-stack#2504]
#### Summary
I used the Getting started guide with docker. Doing so results in a usable stack except for MQTT server. It seems like there is nothing listening on that ports (1881,8881,1883,8883). Connections to these ports result in timeouts.

#### Steps to Reproduce
1. Install the stack using the Getting started guide with docker.
2. Try ton connect to the MQTT server.
3. (Optional) create an api key for connecting to the mqtt server. Same result here.

#### Environment
Release 3.8 on Centos 8

**Comment by johanstokking** [comment]
What is your Gateway Server configuration exactly?

**Comment by laubed** [comment]
```
gs:
  mqtt:
    public-address: 'mydomain:1882'
    public-tls-address: 'mydomain:8882'
  mqtt-v2:
    public-address: 'mydomain:1881'
    public-tls-address: 'mydomain:8881'
```

where mydomain ist my external domain name.
