### ISSUE TITLE
Create devices on extra Join Server

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-stack#2777]
#### Summary

Create devices with root keys on extra Join Servers, like Global Join Server

#### Why do we need this?

Currently, it is impossible to create a device on, for example, Global Join Server and activate it in a TTI Cloud Hosted region via the Console. It needs command-line with a non-trivial configuration. We'll get the same issue in the community network.

We want to promote people to use Global Join Server by default, to put keys in the right place from the start.

#### What is already there? What do you see now?

Console supports two modes on device creation; External Join Server (experience tracked in https://github.com/TheThingsNetwork/lorawan-stack/issues/2119) and cluster-local Join Server. Improvements are already on the way in #2644; this would be an extension of a wizard step.

#### What is missing? What do you want to see?

Multiple options, configurable. For example, in TTI Cloud Hosted:

1. Create on Global Join Server; keys entered will be set to `<tenant>.join.cloud.thethings.industries`. This means a cross-cluster call
2. Create on cluster-local Join Server; keys entered will be set to routing cluster
3. Use third-party Join Server (like Semtech Join Server); existing behavior

#### How do you propose to implement this?

The availability, name and cluster address is configuration. We need the following configuration:

```yaml
console:
  extra-join-servers:
    - name: 'Global Join Server'
      address: 'join.cloud.thethings.industries'
      join-euis:
        - '70B3D57ED0000000/64'
    - name: 'My Custom Join Server'
      address: 'example.com'
      join-euis:
        - '0000000000000000/0'
```

The cluster-local Join Server is implicitly available if the Join Server is enabled in the Console configuration.

The third-party Join Server is always available. We should probably explicitly name it "third-party", because "external" is confusing (extra JS's are also external to the cluster).

#### How do you propose to test this?

1. Disable cluster Join Server in Console: there should only be the option to create devices on the third-party Join Server
2. With 1: configure the cluster Join Server as extra: `extra-join-servers: [{ name: 'Test', address: 'localhost' }]`: there should be two options, with the cluster Join Server as "extra", shown as "Test"

#### Can you do this yourself and submit a Pull Request?

Can review
