### ISSUE TITLE
CUPS  provides a 500 error when acme certs are used

### ISSUE THREAD

**Issue by mattrude** [TheThingsNetwork/lorawan-stack#4265]
#### Summary
When using the `acme` TLS module, the CUPS service is giving a 500 error:

```
Jun 12 05:00:17 console ttn-lw-stack[4516]:  ERROR Server error                             address=console.theodin.network auth.token_id=BQYOQ5QOARIM2GO2AVM456OB7C5EUYTDXZNKMJY auth.token_type=APIKey duration=56.2ms error=error:pkg/basicstation/cups:server_trust (failed to fetch server trust for address `console.theodin.network`) error_cause=remote error: tls: internal error http.method=POST http.path=/update-info http.status=500 namespace=web peer.address=192.168.1.15:58554 request_id=01F7Z9F534KMP263A8FEFDYB7A
```

With the configuration as:
```
tls:
  source: 'acme'
  acme:
    enable: true
    default-host: 'console.theodin.network'
    dir: '/var/lib/ttn/certs'
    email: 'admin@theodin.network'
```

But if you change `tls.source` to `file` CUPS seems to work fine, ie:

```
tls:
  source: 'file'
  certificate: '/etc/letsencrypt/live/console.theodin.network/fullchain.pem'
  key: '/etc/letsencrypt/live/console.theodin.network/privkey.pem'
```

also see: [this forum post](https://www.thethingsnetwork.org/forum/t/48717)

#### Steps to Reproduce

Enable the acme module and try to connect with a CUPS gateway, then switch to the file method and CUPS should work again.

#### Environment

Running TTS V3.13.1
```
The Things Stack for LoRaWAN: ttn-lw-stack
Version:             3.13.1
Build date:          2021-06-04T09:24:40Z
Git commit:          76bc6cf3c
Go version:          go1.16.5
OS/Arch:             linux/arm
```
On Ubuntu running on a Raspberry Pi 4b

```
root@console:/etc/basicstation# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
```

#### How do you propose to test this?

Enable `acme` and see if CUPS works.

#### Can you do this yourself and submit a Pull Request?

Nope, sorry
