### ISSUE TITLE
Join Server fields cannot be updated in Join Server only deployments

### ISSUE THREAD

**Issue by adriansmares** [TheThingsNetwork/lorawan-stack#4941]
#### Summary

Join Server fields (such as the Net ID) cannot be edited in Join Server only environments.

#### Steps to Reproduce

1. Have the following configuration:
```
console:
...
  ui:
...
    is:
      base-url: https://eu1.cloud.thethings.industries/api/v3
    gs:
      enabled: false
    ns:
      enabled: false
    as:
      enabled: false
    js:
      base-url: https://join.cloud.thethings.industries/api/v3
    edtc:
      base-url: https://join.cloud.thethings.industries/api/v3
    qrg:
      base-url: https://join.cloud.thethings.industries/api/v3
```

2. Attempt to edit a Join Server field via the Console

#### What do you see now?

No `POST`/`PUT` request occurs, and on refresh the field is not updated. But the notification does say that the entity has been updated.

This behavior does not seem to exist in deployments where all of the components are available.

#### What do you want to see instead?

The fields should actually be saved.

#### Environment

`v3.16`

#### How do you propose to implement this?

Don't know actually. I guess that the disabled components screw something up.

#### How do you propose to test this?

Reproduce the provided steps.

#### Can you do this yourself and submit a Pull Request?

Can review.
