### ISSUE TITLE
Import end devices from CSV

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-stack#5139]
#### Summary

It looks like this was available before (https://github.com/TheThingsNetwork/lorawan-stack/pull/1448) but now only json is supported.

When we buy off-the-shelf LoRaWAN sensor, the vendors normally send us an Excel file with the DevEUI, AppEUI, AppKey, etc. A file like this can contain hundreds of entries, and I need to register these devices in TTS. The current (planned) solution is to write a python script to iterate through the Excel-csv, and call `ttn-lw-cli` for each one to register the device.

It would be nicer if TTS Console allowed importing devices directly from CSV. After uploading the csv, one would need to choose which columns contain which fields, and then enter default values for the fields that do not exist in the csv. A pre-defined format/column order would also be acceptable as Excel allows easily swapping columns. For default values one could fill the column with the default value in Excel.

I see TTS has a templating feature, but this seems too complicated and I'm not sure this is exactly what I need.

#### Why do we need this?

Make registering a batch of devices from a vendor provided Excel file easier.

#### What is already there? What do you see now?

I can import a batch of devices, but the imported file has to be in TTS JSON format.

#### What is missing? What do you want to see?

Also have a CSV import file format, with the ability to choose which columns contain which values.

#### Environment

TTS v3.17

#### How do you propose to implement this?

Purely on the console using Javascript. But maybe it can also be a ttn-lw-cli feature, but needs to be documented then.

#### How do you propose to test this?

Import a csv file that contains DevEUI, AppEUI, AppKey values.

#### Can you do this yourself and submit a Pull Request?

No

**Comment by NicolasMrad** [comment]
Thank you @jpmeijers for submitting this feature request.
Can you please share with us a sample CSV template that you usually use, with the various fields required?

**Comment by jpmeijers** [comment]
Here are two examples from two different water meter vendors.

[LORAWAN PARAMETER - Bove.xlsx](https://github.com/TheThingsNetwork/lorawan-stack/files/7933482/LORAWAN.PARAMETER.-.Bove.xlsx)
[Lora Axioma.xlsx](https://github.com/TheThingsNetwork/lorawan-stack/files/7933484/Lora.Axioma.xlsx)

**Comment by htdvisser** [comment]
The information in these files alone is not enough to register those end devices. We'd still need to know things like LoRaWAN MAC/PHY version, possibly defaults, etc.

We should probably combine manifest import functionality with the device repository. That way we can also build functionality that understands the format of the manifest of a specific vendor. And we can be certain that those devices work correctly (we don't want someone to import 1000 of sensors only to find out that they don't work).

For the first sensor, we could define the manifest format as:

```yml
manifest:
  parser: csv # Perhaps we can even support xlsx?
  fields:
    dev_id: DeviceId # maybe this should be case-insensitive
    dev_eui: DeviceId
    join_eui: appeui
    app_key: appkey
    attributes: [ ProductName, MeterId ]
```

For the second sensor, it would be something like:

```yml
manifest:
  parser: csv
  fields:
    dev_id: [ Custom identifier, Serial no ] # Alternative idea: specify a list and select the first field that exists.
    dev_eui: Dev EUI
    join_eui: App EUI
    nwk_key: Lora network key
    app_key: Lora app key
    dev_addr: Lora device address
    nwk_s_key: Radio encryption key # ?
    app_s_key: Lora app s key
    attributes: [ ... ]
```

Then in the Console, a user would select the device vendor and model, and then instead of entering the details of a single device, upload the manifest file. The server (Device Claiming Server? End Device Template Converter?) then parses the manifest file and returns the list of end devices about to be registered. The Console can then show the user a nice table and ask for confirmation, after which the registration process starts.
