### ISSUE TITLE
Support multiple LoRa standard channels on device

### ISSUE THREAD

**Issue by virtualguy** [TheThingsNetwork/lorawan-stack#6526]
### Summary

Gateways with multiple concentrators (i.e. a 16ch gateway) can listen on more than one LoRa standard channel but this is not supported in the frequency plan [definitions](https://github.com/TheThingsNetwork/lorawan-frequency-plans)

```
lora-standard-channel: 
  frequency: 915900000
  data-rate: 6
  radio: 0
```

### Current Situation

Only a single LoRa standard channel is configurable. A previous work around to specify the extra channels as normal uplink-channels with only a single data rate is no longer supported due to #6182

### Why do we need this? Who uses it, and when?

Devices wanting to use more than one sub band for uplinks and wide channels

### Proposed Implementation

Change lora-standard-channels to a list and then support added to the stack

```
lora-standard-channels: 
  - frequency: 915900000
  data-rate: 6
  radio: 0
  - frequency: 917500000
  data-rate: 6
  radio: 0
```

Alternatively allow a device to support multiple frequency plans like a gateway (frequency_plan_ids) and set the desired channels to the full set of channels across the plans

### Contributing

- [X] I can help by doing more research.
- [X] I can help by implementing the feature after the proposal above is approved.
- [X] I can help by testing the feature before it's released.

### Code of Conduct

- [X] I agree to follow TTN's [Community Code of Conduct](https://github.com/TheThingsNetwork/Manifesto/blob/master/CodeOfConduct.md).
