### ISSUE TITLE
Support Generation of router_config for 16/64 Channel Basic Station gateways

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsNetwork/lorawan-stack#761]
#### Summary

Support gateway config for gateways with >8 channels.

#### Why do we need this?

This is to support configuration of 16 ch gateways Ex: TTOG US Version and potentially higher channels.

#### What is already there? What do you see now?

- `pfconfig` supports only one `SX1301_conf` object.
- `lns` generates only one `SX1301_conf`.

#### What is missing? What do you want to see?

- Support combining channels from frequency plans from different frequency plans and pass that to the Basic Station.

#### Environment

All

#### How do you propose to implement this?

- [x] API: introduce a repeated string frequency_plan_ids to Gateway. Falls in scope of this issue
- [x] ER: handle new field as described in #1353 (comment) (i.e. staying backward compatible with clients who only know frequency_plan_id, potentially having them accidentally reset multiple plans). Falls in scope of this issue
GS
- [x] Support multiple frequency plans in Basic Station LNS. Falls in scope of this issue
  - [x] promote basicstation `router_config` to `pkg/pfconfig`
  - [x] make `sx1301` a slice.
  - [x] Generate one `SX1301_conf` object for each configured frequency plan.
  - [x] Update the `hwspec` field of the `router_config` for basicstation.
- [x] Support multiple frequency plans in the scheduler. This needs a separate issue, scoped to same band frequency plans, referencing #1394 to support mixed bands
- [x] GCS: add support to return a UDP packet forwarder global_conf.json with multiple concentrator support. This needs a separate issue: #1837 

#### Can you do this yourself and submit a Pull Request?

Yes.

cc: @htdvisser

**Comment by htdvisser** [comment]
Blocked on #762

**Comment by KrishnaIyer** [comment]
Back when I worked on this, I noticed that we extract a single SX1301 field from one Frequency plan.
We probably need to edit the `yaml` ( except the `band_id` field), and add a top level key with n arrays where n=no of concentrators.
```
band-id: EU_863_870
concentrators:
- uplink-channels:
  - frequency: 868100000
    min-data-rate: 0
    max-data-rate: 5
    radio: 1
  - frequency: 868300000
    min-data-rate: 0
    max-data-rate: 5
    radio: 1
  - frequency: 868500000
    min-data-rate: 0
    max-data-rate: 5
    radio: 1
  - frequency: 867100000
    min-data-rate: 0
    max-data-rate: 5
    radio: 0
  - frequency: 867300000
    min-data-rate: 0
    max-data-rate: 5
    radio: 0
  - frequency: 867500000
    min-data-rate: 0
    max-data-rate: 5
    radio: 0
  - frequency: 867700000
    min-data-rate: 0
    max-data-rate: 5
    radio: 0
  - frequency: 867900000
    min-data-rate: 0
    max-data-rate: 5
    radio: 0
  downlink-channels:
  - frequency: 868100000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 868300000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 868500000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 867100000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 867300000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 867500000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 867700000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 867900000
    min-data-rate: 0
    max-data-rate: 5
  lora-standard-channel:
    frequency: 868300000
    data-rate: 6
    radio: 1
  fsk-channel:
    frequency: 868800000
    data-rate: 7
    radio: 1
  radios:
  - enable: true
    chip-type: SX1257
    frequency: 867500000
    rssi-offset: -166
    tx:
      min-frequency: 863000000
      max-frequency: 870000000
  - enable: true
    chip-type: SX1257
    frequency: 868500000
    rssi-offset: -166
  clock-source: 1
- uplink-channels:
  - frequency: 868100000
    min-data-rate: 0
    max-data-rate: 5
    radio: 1
  - frequency: 868300000
    min-data-rate: 0
    max-data-rate: 5
    radio: 1
  - frequency: 868500000
    min-data-rate: 0
    max-data-rate: 5
    radio: 1
  - frequency: 867100000
    min-data-rate: 0
    max-data-rate: 5
    radio: 0
  - frequency: 867300000
    min-data-rate: 0
    max-data-rate: 5
    radio: 0
  - frequency: 867500000
    min-data-rate: 0
    max-data-rate: 5
    radio: 0
  - frequency: 867700000
    min-data-rate: 0
    max-data-rate: 5
    radio: 0
  - frequency: 867900000
    min-data-rate: 0
    max-data-rate: 5
    radio: 0
  downlink-channels:
  - frequency: 868100000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 868300000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 868500000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 867100000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 867300000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 867500000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 867700000
    min-data-rate: 0
    max-data-rate: 5
  - frequency: 867900000
    min-data-rate: 0
    max-data-rate: 5
  lora-standard-channel:
    frequency: 868300000
    data-rate: 6
    radio: 1
  fsk-channel:
    frequency: 868800000
    data-rate: 7
    radio: 1
  radios:
  - enable: true
    chip-type: SX1257
    frequency: 867500000
    rssi-offset: -166
    tx:
      min-frequency: 863000000
      max-frequency: 870000000
  - enable: true
    chip-type: SX1257
    frequency: 868500000
    rssi-offset: -166
  clock-source: 1
```
